name: Run Scanner

on:
  pull_request:
  #push:

jobs:
  scan-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install SFDX CLI and Scanner
        run: |
          npm install sfdx-cli -g
          sfdx plugins:install @salesforce/sfdx-scanner
      # Determine changed Apex classes
      - name: Get changed Apex classes
        id: changed-classes
        run: |
          echo "##[set-output name=changed_classes;]$(git diff --name-only HEAD^ HEAD | grep '.cls$')"
          
      - name: Apex static analysis on changed classes
        if: ${{ steps.changed-classes.outputs.changed_classes != '' }} # Run only if changed classes exist
        run: |
          sfdx scanner run --target "unpackaged/main/default/classes/${{ steps.changed-classes.outputs.changed_classes }}" --pmdconfig "unpackaged/main/default/ruleset.xml" -f html --outfile 'apexScanResults.html'
      
      # start for adding report link as comment    
      - name: Apex static analysis
        run: |
            sfdx scanner run --target 'PMDConfigureSFDC/force-app/main/default/classes/' --pmdconfig "PMDConfigureSFDC/force-app/main/default/pmd/pmdrules.xml" -f html --outfile 'apexScanResults.html'
          
      - name: Upload PMD Report
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
           name: scanner-output-${{ github.run_number }}.html
           path: apexScanResults.html
        
      - name: Output artifact URL
        run:  echo 'Artifact URL is ${{ steps.artifact-upload-step.outputs.artifact-url }}'
