name: Run Scanner

on:
  pull_request:
  #push:

jobs:
  scan-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install SFDX CLI and Scanner
        run: |
          npm install sfdx-cli -g
          sfdx plugins:install @salesforce/sfdx-scanner
      # Determine changed Apex classes
      - name: Get changed Apex classes
        id: changed-classes
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "/PMDConfigureSFDC/force-app/main/default/classes/")
          echo "::set-output name=changed_files::$CHANGED_FILES"
          
      - name: Apex static analysis on changed classes
        run: |
          sfdx scanner run --target "/PMDConfigureSFDC/force-app/main/default/classes/" --pmdconfig "/PMDConfigureSFDC/force-app/main/default/pmd/pmdrules.xml" -f html --outfile 'apexScanResults.html'
      
      # start for adding report link as comment    
      - name: Apex static analysis
        run: |
            sfdx scanner run --target 'PMDConfigureSFDC/force-app/main/default/classes/' --pmdconfig "PMDConfigureSFDC/force-app/main/default/pmd/pmdrules.xml" -f html --outfile 'apexScanResults.html'
          
      - name: Upload PMD Report
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
           name: scanner-output-${{ github.run_number }}.html
           path: apexScanResults.html
        
      - name: Output artifact URL
        run:  echo 'Artifact URL is ${{ steps.artifact-upload-step.outputs.artifact-url }}'
